### PR TITLE
skink svcomp16 wrapper

### PR DESCRIPTION
**Pull request by altmattr**
This is our BenchExec wrapper for skink.

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Could you please add a license to the file? We would prefer the Apache 2.0 License, if possible.

Does your tool need to be given the propery file? If so, you need to overwrite the `cmdline` function.

Is there a possibility to extract the version from the tool? With the hardcoded version number, this could lead to confusing and misleading benchmark results if a newer version of your tool is used and BenchExec labels it with "0.314". Thus I think it would be better to automatically get the correct version number or remove it.

**Comment by altmattr** [comment]
I have added a licence and I am double checking we don't need a property file.  At the moment skink does not report its version but that is something we aim to fix soon.

**Comment by PhilippWendler** [comment]
Version is not required but of course nice to have. Just tell me when you know whether you need a property file and I'll merge this PR.

**Comment by altmattr** [comment]
I can confirm we don't need the property file.

**Comment by PhilippWendler** [comment]
Could you please still remove the hardcoded version number? As I said, I think the hardcoded number is worse than having no number as it could lead to a wrong number being shown.

**Pull request merged**
