### PR TITLE
wrapper script for AProVE

### PR DESCRIPTION
**Pull request by cryingshadow**
Adapted from the ufo script - not sure whether this runs since we were not able to install BenchExec (no up-to-date Linux machine available).

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Does your tool use the SV-Comp property files? If yes, you should overwrite the `cmdline` function and use the propertyfile parameter to pass the property to your tool.

For the true/false return values from the `determine_result` function, please use the constants from the `result` module instead of strings.

Does your tool have a version number you can extract automatically? Then it would be great to overwrite `version` and do so (makes it nicer for users). You can probably simply call `_version_from_tool`.

**Comment by cryingshadow** [comment]
Thanks for the hints!

Do you have a correct example file that I could adapt?

**Comment by kfriedberger** [comment]
> For the true/false return values from the determine_result function, 
> please use the constants from the result module instead of strings.

--> https://github.com/dbeyer/benchexec/blob/master/benchexec/tools/rand.py#L40

> Does your tool have a version number you can extract automatically?

--> https://github.com/dbeyer/benchexec/blob/master/benchexec/tools/cbmc.py#L37

**Comment by cryingshadow** [comment]
Adapted the file to use the result constants. Currently, our tool does not provide a version number and we only participate in one category (both might still change, though).

**Comment by PhilippWendler** [comment]
Thanks.

**Pull request merged**
