### PR TITLE
add symbiotic2 tool

### PR DESCRIPTION
**Pull request by mchalupa**
Add wrapper script for symbiotic2

Signed-off-by: Marek Chalupa <mchqwerty@gmail.com>

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Is the `--sv-comp` option always necessary or is it just the specific configuration you want to run in SV-Comp? The typical way to handle configuration options of tools within BenchExec is to allow the user to specify them in the benchmark configuration file, not have them hard-coded in the tool wrapper
(except if your tool absolutely requires these options).
This makes the wrapper script added to BenchExec useful for your tool in general, not only specifically for SV-Comp. Thus I would suggest to remove the `--sv-comp` option and specify it in the system description together with your additional parameters (for machine model etc.).

**Comment by mchalupa** [comment]
It specifies just the output format and it also tells symbiotic to read the property file, so I'd need to fix that and send a new link to the tool for pre-run. Is the system description required for the pre-run?

**Comment by PhilippWendler** [comment]
If `--sv-comp` is a general option that always needs to specified anyway because for example the `determine_result` function needs this output then it should be left in and there is no need to change (e.g., for CBMC we have `--xml-ui` in the wrapper because the wrapper expects the output to be in XML format).

`--prp` is used the way it should be anyway.

For questions regarding SV-Comp such as what is needed for the pre-run phase, please ask on the SV-Comp mailing list (I cannot answer this).

**Comment by mchalupa** [comment]
we changed the script behavior and also we bumped the tool's version from 2 to 3, so I'm closing this one and will create new one

**Pull request closed without merging**
