### PR TITLE
Add wrapper script for HIPrec

### PR DESCRIPTION
**Pull request by muoitranduc**
This is a wrapper script for the HIPrec tool available at http://loris-7.ddns.comp.nus.edu.sg/~project/hiprec/ . This script is part of our competition submission "HIPrec: Verifying Recursive Programs with an Unfolding-based Satisfiability Solver".

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Does your tool need to be given the propery file? If so, you need to use the `propertyfile` parameter of the `cmdline` function.

Does your tool have a version number you can extract automatically? Then it would be great to overwrite `version` and do so (makes it nicer for users, but is not required). You can probably simply call `self._version_from_tool`.

**Comment by muoitranduc** [comment]
Dear Philipp Wendler,
Please note that the commit on: https://github.com/muoitranduc/benchexec/commit/f30999d571e73e6b3f284de9132836c8c1b447e3
is not the final version. We just notice there are some issues on the wrapper script. We are fixing it asap. Sorry for any inconvenience.

**Comment by PhilippWendler** [comment]
No problem. GitHub does not even notify me for new commits anyway, so just add a comment when you are ready for merging.

**Comment by muoitranduc** [comment]
Dear Philipp Wendler,
We added some restrictions in the latest version. It's failed on the codacy checking, but without any issue. Please take a look at it. If this commit is truly bug-free, please help in merging it. Otherwise, all feedback are welcomed since I'm quite inexperienced in this stuff.
Thanks.

**Comment by PhilippWendler** [comment]
Looks good so far, thanks for updating the request. Please ignore the Codacy check failure, I don't really know what they understand under "commit quality", but they have some useful static-analysis checks (like the one that found the undeclared variable above), that's why it is enabled.

From my point it could be merged, I have just two questions which maybe you would like to address (both optional though):

Does your tool need to be given the propery file? If so, you need to use the `propertyfile` parameter of the `cmdline` function.

Does your tool have a version number you can extract automatically? Then it would be great to overwrite `version` and do so (makes it nicer for users, but is not required). You can probably simply call `self._version_from_tool`.

**Comment by muoitranduc** [comment]
Does your tool need to be given the propery file? If so, you need to use the propertyfile parameter of the cmdline function.
--> Our tool does not require a property file to run.

Does your tool have a version number you can extract automatically? Then it would be great to overwrite version and do so (makes it nicer for users, but is not required). You can probably simply call self._version_from_tool.
--> For now, I guess the tool does not have a version number so we can ignore it.

Many thanks for your feedback.

TM.

**Comment by PhilippWendler** [comment]
Thanks for answering, I will merge the pull request.

**Pull request merged**
