### PR TITLE
first attempt at seahorn wrapper

### PR DESCRIPTION
**Pull request by agurfinkel**
Based on the [ufo.py](https://github.com/dbeyer/benchexec/blob/master/benchexec/tools/ufo.py) sample provided in Dirk's email.
Unfortunately, I have no way of testing this. 

I could not find a way to pass specific flags for property, counterexamples, and platform.

### CODE REVIEW

**Comment by PhilippWendler** [comment]
The typical way to handle configuration options of tools within BenchExec is to allow the user to specify them in the benchmark configuration file, not have them hard-coded in the tool wrapper
(except if your tool absolutely requires these options).
This makes the wrapper script added to BenchExec useful for your tool in general, not only specifically for SV-Comp. For example, benchmarking users could then choose the target path for the counterexample file themselves.
Thus, could you please remove `--cex` and `-p inline:no_inline`?

The property (file) gets passed to the `cmdline` function in the `propertyfile` parameter, so if your tools wants to get the property passed, you can use this parameter. Any further options such as platform are to be defined in the benchmark configuration file.

You should be able to test this using any Linux machine (even a VM). Are there any specific problems you are experiencing?

**Comment by PhilippWendler** [comment]
Does your tool have a version number you can extract automatically? Then it would be great to overwrite `version` and do so (makes it nicer for users). You can probably simply call `_version_from_tool`.

**Comment by agurfinkel** [comment]
Hey, we are working on updating the wrapper. This, however, also requires changes in the tool itself, so it has been taken a while.

**Comment by agurfinkel** [comment]
@PhilippWendler please try the pull request again.

**Comment by PhilippWendler** [comment]
Does your tool need to get passed the property file? I assume yes because you asked for it. In this case you should use the `propertyfile` parameter in the `cmdline` function.

Apart from this it looks good now, thanks.

**Comment by lememta** [comment]
@PhilippWendler we have added the support for propertyfile. Can you pull request?

**Pull request merged**
