### PR TITLE
Add wrapper script for the LCTD verification tool

### PR DESCRIPTION
**Pull request by OlliSaarikivi**
This is a wrapper script for the LCTD tool available at http://users.cse.aalto.fi/osaariki/lctd-svcomp/ . This script is part of our competition contribution "LCTD: Tests-Guided Proofs for C Programs on LLVM".

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Does your tool need to be given the propery file? If so, you need to use the `propertyfile` parameter of the `cmdline` function.

You should probably also append `options` to the command line, otherwise all parameters defined by users will be ignored.

Does your tool have a version number you can extract automatically? Then it would be great to overwrite `version` and do so (makes it nicer for users, but is not required). You can probably simply call `self._version_from_tool`.

**Comment by OlliSaarikivi** [comment]
The tool does not currently support the property files (i.e. it just checks for reachability of calling the LLVM builtin "__assert_fail" function).

The "lctdsvcomp" shell script that this wrapper script calls doesn't have support for passing options to the components of the tool. Would you like for me to still append the options in the wrapper script? Currently trying to pass any options would cause the tool to crash.

The tool doesn't currently have a version number output.

**Comment by PhilippWendler** [comment]
Passing options or at least asserting that `options` is empty would be good. Otherwise someone might try to specify additional options, which would get silently swallowed.

Passing a property file is not necessary if not supported by the tool, same goes for using the version number.

**Comment by OlliSaarikivi** [comment]
I added an assertion that `options` is empty to make it clear none are currently supported.

**Pull request merged**
