### PR TITLE
First commit for PAC-MAN wrapper

### PR DESCRIPTION
**Pull request by usefulalgorithm**
I didn't run any test on this wrapper script. The team is still working on getting the rest of the Competition Contributions paper done, so this will probably have to wait...

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Please add a comment when you are finished and want to get this merged.

**Comment by usefulalgorithm** [comment]
OK, thank you!

2015-10-30 16:42 GMT+08:00 Philipp Wendler <notifications@github.com>:

> Please add a comment when you are finished and want to get this merged.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dbeyer/benchexec/pull/61#issuecomment-152461555>.
>



-- 
Andy Lii

NTU GIEE, Taiwan
usefulalgorithm@gmail.com

**Comment by usefulalgorithm** [comment]
Please merge this commit, thanks!

**Comment by PhilippWendler** [comment]
Does your tool use the SV-Comp property files? If yes, you should overwrite the `cmdline` function and use the propertyfile parameter to pass the property to your tool.

Does your tool have a version number you can extract automatically? Then it would be great to overwrite `version` and do so (makes it nicer for users, but is not required). You can probably simply call `self._version_from_tool`.

**Comment by usefulalgorithm** [comment]
2015-10-31 17:55 GMT+08:00 Philipp Wendler <notifications@github.com>:

> Does your tool use the SV-Comp property files? If yes, you should
> overwrite the cmdline function and use the propertyfile parameter to pass
> the property to your tool.
>
No, our tool doesn't use the SV-Comp property files.


> Does your tool have a version number you can extract automatically? Then
> it would be great to overwrite version and do so (makes it nicer for
> users, but is not required). You can probably simply call
> self._version_from_tool.
>
Well, we don't have a version number...

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dbeyer/benchexec/pull/61#issuecomment-152719270>.
>



-- 
Andy Lii

NTU GIEE, Taiwan
usefulalgorithm@gmail.com

**Comment by PhilippWendler** [comment]
That's ok, just wanted to be sure.

**Pull request merged**
