### PR TITLE
DepthK Class to work on Benchexec

### PR DESCRIPTION
**Pull request by WilliameRocha**
ESBMC+DepthK Tool.

### CODE REVIEW

**Comment by PhilippWendler** [comment]
Could you please add a license to the file? We would prefer the Apache 2.0 License, if possible.

Does your tool use the SV-Comp property files? If yes, you should use the `propertyfile` parameter in the `cmdline` function to pass it to your tool.

The path in `executable` seems to be specific to your system, or does DepthK require this directory layout (i.e., executing benchmarks only in a directory from which the tool is reachable in `../../depthk`)? If not, could you please remove the `../../depthk/` part so users can run in easly without requiring a specific directory structure?

**Comment by WilliameRocha** [comment]
**Could you please add a license to the file? We would prefer the Apache 2.0 License, if possible.**
  Apache 2.0 License was added.

**Does your tool use the SV-Comp property files? If yes, you should use the propertyfile parameter in the cmdline function to pass it to your tool.**
 Yes, the form to send propertyfile as parameter is -c propertyfile.prp, for example: depthk-wrapper.sh -c ALL.prp cFile

 During my tests, i used the ``` <propertyfile>${inputfile_path}/ALL.prp</propertyfile> 
parameter on xml file passed to wrapper through Benchexec.

**The path in executable seems to be specific to your system, or does DepthK require this directory layout (i.e., executing benchmarks only in a directory from which the tool is reachable in ../../depthk)? If not, could you please remove the ../../depthk/ part so users can run in easly without requiring a specific directory structure?**

The tool does not require a specific directory,

**Comment by PhilippWendler** [comment]
Thanks for the changes. `<propertyfile>` is indeed the supposed way to pass properties, so you should properly add something like '['-c', propertyfile]' to the command line if `propertyfile` is not None (otherwise your tool won't see the property file).

**Comment by WilliameRocha** [comment]
Dear Philipp,

Sorry. I couldn't understand your claim.

DepthK wrapper script is already prepared to pass properties in the command-line as follows:

$depthk-wrapper.sh -c ALL.prp verification_task_file

Is there something wrong in our call?

Many thanks for your support.

-- Williame

**Comment by kfriedberger** [comment]
Maybe Philipp's intent was something like this:

Please replace line 60:
`return [os.path.relpath(executable, start=workingDir)] + options + [os.path.relpath(sourcefile, start=workingDir)]
`
by the following one:
`return [os.path.relpath(executable, start=workingDir)] + options + ['-c', propertyfile, os.path.relpath(sourcefile, start=workingDir)]
`
and remove any self-written option for the property-file from your XML-file.
Then BenchExec will automatically set the property-file and everything works.

-- Karlheinz

**Comment by WilliameRocha** [comment]
Dear Philip,

the line 60 was updated.

**Comment by WilliameRocha** [comment]
Dear Philipp, 

There is still something to do?

Thanks.

**Comment by PhilippWendler** [comment]
Sorry for the delay, yes, this is what I meant.

Does your tool always require a property file? If not, why not make it optional and add it to the command line only if specified (i.e., if it is not None)? Currently, it will crash if the user specifies no property file.

**Comment by WilliameRocha** [comment]
Hi Philipp,

Yeah. Our tool does require a property file to be specified in the command-line.

Were you able to run our tool? Is there something else that we have to do?

Many thanks for your support.

-- Williame

**Comment by PhilippWendler** [comment]
I did not test it, but the wrapper looks good. Thanks for answering and addressing my questions, I will merge this now.

**Comment by WilliameRocha** [comment]
Thaks for your support, Philipp.

:-)

**Pull request merged**
